require:
  - rubocop-rspec

inherit_from: .rubocop_todo.yml

AllCops:
  NewCops: disable
  Exclude:
    - .bundle/**/*
    - vendor/**/*
    - package/*
    - Rakefile

# Impossible to satisfy these rules in specs
RSpec/ExpectInHook:
  Enabled: false

RSpec/NestedGroups:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

RSpec/SubjectStub:
  Enabled: false

# disabled, %<> should not be used in translatable strings
# but otherwise it does not matter much
Style/FormatStringToken:
  Enabled: false
