
# See https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions

name: CI

on: [push, pull_request]

jobs:
  Tests:
    runs-on: ubuntu-latest
    container: registry.opensuse.org/yast/sle-15/sp3/containers/yast-ruby:latest

    steps:

    - name: Git Checkout
      uses: actions/checkout@v2

    # just for easier debugging...
    - name: Inspect Installed Packages
      run: rpm -qa | sort

    - name: Unit Tests
      run: rake test:unit
      # enable code coverage reporting
      env:
        COVERAGE: 1

    # send the coverage report to coveralls.io
    - name: Coveralls Report
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}

  Rubocop:
    runs-on: ubuntu-latest
    container: registry.opensuse.org/yast/sle-15/sp3/containers/yast-ruby:latest

    steps:

    - name: Git Checkout
      uses: actions/checkout@v2

    - name: Add SCC Codestyle
      run: gem install --no-document scc-codestyle -v 0.1.4

    - name: Proper Rubocop Version
      run: rm /etc/alternatives/rubocop && ln -s /usr/lib64/ruby/gems/*/gems/rubocop-0.52.1/bin/rubocop /etc/alternatives/rubocop

    - name: Rubocop
      run: rubocop

  Package:
    runs-on: ubuntu-latest
    container: registry.opensuse.org/yast/sle-15/sp3/containers/yast-ruby:latest

    steps:

    - name: Git Checkout
      uses: actions/checkout@v2

    - name: Package Build
      run: yast-ci-ruby -o package

  # downloading the Docker image takes some time so bundling several fast
  # checks into one job avoids that overhead
  Checks:
    runs-on: ubuntu-latest
    container: registry.opensuse.org/yast/sle-15/sp3/containers/yast-ruby:latest

    steps:

    - name: Git Checkout
      uses: actions/checkout@v2

    - name: POT Check
      run: rake check:pot
